### ISSUE TITLE
8.0.28解密失败

### ISSUE THREAD

**Issue by monkeycc** [greycodee/wechat-backup#19]
1234567890ABCDEF拼接123456789

1234567890ABCDEF123456789
再32位 小写
5148877b8e44e0da2878...

然后前7位
5148877

数据库提示密码错误

小米MIUI系统
手机 3个IMEI 都不行

**Comment by greycodee** [comment]
你获取到uin码了吗？
使用 1234567890ABCDEF 拼接 uin 码

**Comment by monkeycc** [comment]
auth_info_key_prefs.xml 
_auth_uin获取uin值

xxxx = uin值
# 开始拼接
1234567890ABCDEFxxxx

再32位 小写
5148877b8e44e0da2878...

然后前7位
5148877

数据库密码提示错误

**Comment by greycodee** [comment]
是直接用docker容器解密的吧？

**Comment by monkeycc** [comment]
不是
我现在试试docker容器解密

**Comment by monkeycc** [comment]
不是
真机复制黏贴出来
win本地解密
用SQLiteStudio数据库

**Comment by greycodee** [comment]
你看下REDME，直接用docker解密
