### ISSUE TITLE
解密失败

### ISSUE THREAD

**Issue by yangchuansheng** [greycodee/wechat-backup#2]
2022/06/25 07:58:21 开始解密...
2022/06/25 07:58:22 解密失败: Error: near line 7: stepping, file is not a database (26)
Error: near line 8: stepping, unknown database WxFileIndexplain (1)
Error: near line 9: stepping, no such database: WxFileIndexplain (1)

**Comment by yangchuansheng** [comment]
微信版本 8.0.22，还用了 wx 模块，是不是数据库密码不对

**Comment by greycodee** [comment]
@yangchuansheng 出现 `file is not a database`  一般都是密码不对。你是用 uin 拼接来解密的吗？

**Comment by greycodee** [comment]
@yangchuansheng 是什么手机，如果是小米的，一般 IMEI 直接用 `1234567890ABCDEF` 代替就可以。还有密码要**小写的字母**

**Comment by yangchuansheng** [comment]
> @yangchuansheng 是什么手机，如果是小米的，一般 IMEI 直接用 `1234567890ABCDEF` 代替就可以。还有密码要**小写的字母** 

一加8T，我用这个代替了还是不对

**Comment by yangchuansheng** [comment]
> @yangchuansheng 是什么手机，如果是小米的，一般 IMEI 直接用 `1234567890ABCDEF` 代替就可以。还有密码要**小写的字母** 

你说的我都试过了，不知道为啥不对，能不能加个微信交流下

**Comment by greycodee** [comment]
@yangchuansheng 微信号：greycodee

**Comment by greycodee** [comment]
通过微信联系后，最后用 1234567890ABCDEF 拼接 uin 得出密码了

**Comment by falcolee** [comment]
补充一点，第三种秘钥获取方式，在/data/data/com.tencent.mm/shared_prefs/auth_info_key_prefs.xml中的_auth_key并不一定是真正的uid，以我为例8.0.27 miui12.5系统下在/data/data/com.tencent.mm/MicroMsg下的 systemInfo.cfg 文件中，通过这个https://github.com/Heyxk/notes/issues/1#issuecomment-941133328 java文件解密得到正确的uid和imei
