### ISSUE TITLE
有没有开放前端代码的想法呢？

### ISSUE THREAD

**Issue by hedonihilist** [greycodee/wechat-backup#27]
按照作者写的教程成功把微信的数据导出了，这个仓库可太有用了！

导出成功之后感觉前端可以做一点点改进，比如往上滚动到顶部自动加载下一页，增大显示聊天记录的页面，一页显示更多信息等等。

试着找了一下前端的代码发现混淆过，好像是通过某种框架导出的（不是前端程序员，没怎么折腾过）。我觉得开发前端代码能够让自定义过程更加轻松，同时也能吸引到更多人使用这个项目，不知道作者有没有开放前端代码的想法呢？

**Comment by greycodee** [comment]
https://github.com/wechat-bak/wechat-bak-web

在这，不过代码很烂凑合看吧，现在也没什么时间维护了

**Comment by hedonihilist** [comment]
> 

原来在这个仓库，一时没有找到，空了改改
