### ISSUE TITLE
【开发中】为了简化流程，弄一个一键脚本

### ISSUE THREAD

**Issue by greycodee** [greycodee/wechat-backup#3]
由于本人是小米手机，所以只能做 MIUI 的一键脚本。
脚本大致使用流程：
1. 手机系统自带备份工具来备份微信数据
2. 执行一键脚本，进行：
  - 自动进行 .bak 文件解包
  - 自动划分所有登陆过的微信号文件
  - 自动解密数据库
  - 自动语音转码

**Comment by greycodee** [comment]
进度30%

**Comment by XuzhiChan** [comment]
可以的老铁，应该顺便放个打赏码。

**Comment by jasoncrux** [comment]
ios能用么

**Comment by greycodee** [comment]
> ios能用么

暂时不能，，后续应该会弄下

**Comment by greycodee** [comment]
> 可以的老铁，应该顺便放个打赏码。

@XuzhiChan 哈哈，谢谢支持
