### ISSUE TITLE
8.0.40 未查询到个人信息

### ISSUE THREAD

**Issue by jasonchio-cn** [greycodee/wechat-backup#33]
两个数据库文件都已经解密

在run main.go之后报了如下错误
2023/10/11 00:48:39 未查询到个人信息,Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2023/10/11 00:48:39 未查询到图片索引表名,Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

**Comment by jsijea** [comment]
解决了吗
