### ISSUE TITLE
是否可以支持仅db文件的解析展示？

### ISSUE THREAD

**Issue by tenwx** [greycodee/wechat-backup#4]
RT，前几年由于年少无知，仅仅备份并解密了EnMicroMsg.db文件，其他的一概没保留，所以想问下是否可以兼容这种场景？另外程序是否可以预编译发布到Release上，非技术党。。

**Comment by greycodee** [comment]
> 仅仅备份并解密了EnMicroMsg.db文件，其他的一概没保留，所以想问下是否可以兼容这种场景？

你是说只显示 EnMicroMsg.db 的文本内容？这个的话暂时只要新建一个 WxFileIndex.db,然后两个文件放在一起，程序就可以运行了。

> 另外程序是否可以预编译发布到Release上，非技术党。。

过两天我再打包发 Release 吧

**Comment by greycodee** [comment]
由于使用了cgo，无法交叉编译发 Release，你可以本地安装 go 环境后在本地编译运行
