### ISSUE TITLE
关于食用方法的学习

### ISSUE THREAD

**Issue by Jerrymics** [greycodee/wechat-backup#7]
感谢大佬的项目
奈何小弟太菜，学go不精，目前是EnMicroMsg.db文件解密成功，到使用流程的第六步的时候，我开启了我的报错之旅（哈哈哈）
以下是我认为的项目运行命令
![image](https://user-images.githubusercontent.com/46161570/178600647-5622e741-ea08-4cfd-a966-62edeafd6ff1.png)
以下是我存储微信备份文件的文件夹内容
![image](https://user-images.githubusercontent.com/46161570/178601002-b32f5a40-a252-429f-b294-d94d0fde3b81.png)
 还请大佬看看 我哪里操作有问题

**Comment by greycodee** [comment]
WxFileIndex_plain.db 大小为 0 kb，原始文件大小是多少？

**Comment by Jerrymics** [comment]
> WxFileIndex_plain.db 大小为 0 kb，原始文件大小是多少？

EnMicroMsg.db 是36266 kb

**Comment by greycodee** [comment]
WxFileIndex_plain.db 里面没有数据表，建议重新转移下这个db然后解密

**Comment by greycodee** [comment]
最新master已修复，本地重新 pull 下代码
